import Link from "next/link";
import Image from "next/image";
import { Box, Plus, Pencil } from "lucide-react";
import { ProductPrice } from "@/components/product/ProductPrice";
import { ArchiveProductButton } from "@/components/admin/ArchiveProductButton";
import { ProductAvailabilityEditor } from "@/components/admin/ProductAvailabilityEditor";
import { AdminProductFilter } from "@/components/admin/AdminProductFilter";
import { getAdminProductFilterOptions, getAdminProducts, type AdminProductFilters } from "@/services/admin-product.service";
export default async function AdminProductsPage({ searchParams }: { searchParams: Promise<{ query?: string; categoryId?: string; brandId?: string; status?: string; type?: string; page?: string }> }) {
  const params = await searchParams;
  const filters: AdminProductFilters = { query: params.query, categoryId: params.categoryId, brandId: params.brandId, status: params.status === "ACTIVE" || params.status === "DRAFT" || params.status === "ARCHIVED" ? params.status : undefined, type: params.type === "IN_STOCK" || params.type === "PREORDER" ? params.type : undefined };
  const [products, options] = await Promise.all([getAdminProducts(filters), getAdminProductFilterOptions()]);
  const pages = Math.max(1, Math.ceil(products.length / 20));
  const page = Math.max(1, Math.min(pages, Math.floor(Number(params.page)) || 1));
  const visible = products.slice((page - 1) * 20, page * 20);
  const link = (target: number) => { const query = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value && key !== "page") query.set(key, value); }); query.set("page", String(target)); return `/admin/products?${query}`; };
  return <main>
    <div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="flex items-center gap-3 text-3xl font-bold"><Box className="text-blue-600" size={30} />Quản lý sản phẩm</h1><p className="mt-2 text-sm text-zinc-500">Quản lý danh sách figure, mô hình có sẵn và đặt trước.</p></div><Link href="/admin/products/create" className="inline-flex items-center gap-2 rounded-md bg-[var(--brand)] px-5 py-3 text-sm font-semibold text-white"><Plus size={18} />Thêm sản phẩm</Link></div>
    <AdminProductFilter categories={options.categories} brands={options.brands} values={filters} />
    <section className="mt-5 overflow-hidden rounded-lg border border-zinc-200 bg-white"><div className="flex items-center justify-between gap-3 border-b border-zinc-200 p-4 text-sm"><p>Tổng <strong>{products.length} sản phẩm</strong></p><span className="text-xs text-zinc-500">20 sản phẩm / trang</span></div><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-xs"><caption className="sr-only">Danh sách sản phẩm quản trị</caption><thead><tr>{["Hình ảnh", "Tên sản phẩm", "Danh mục", "Thương hiệu", "Giá", "Tồn kho", "Trạng thái", "Loại hàng", "Thao tác"].map(label => <th key={label} className="px-3 py-4">{label}</th>)}</tr></thead><tbody>{visible.map(product => <tr key={product.id} className="border-t border-zinc-100 hover:bg-blue-50/40">
      <td className="p-3"><div className="relative size-16 overflow-hidden rounded bg-zinc-50">{product.images[0] && <Image src={product.images[0].url} alt={product.name} fill sizes="64px" className="object-contain" />}</div></td>
      <td className="max-w-60 p-3"><Link href={`/admin/products/${product.id}/edit`} className="text-sm font-semibold hover:text-blue-600">{product.name}</Link><p className="mt-1 line-clamp-1 text-[10px] text-zinc-500">{product.slug}</p></td><td className="max-w-36 p-3">{product.category?.name ?? "—"}</td><td className="p-3">{product.brand?.name ?? "—"}</td><td className="whitespace-nowrap p-3"><ProductPrice price={product.price} /></td><td className={`p-3 font-bold ${product.stock ? "text-emerald-600" : "text-red-500"}`}>{product.stock}</td><td className="p-3"><span className={`rounded-md px-2 py-1.5 ${product.status === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : "bg-zinc-100 text-zinc-500"}`}>{product.status}</span></td><td className="p-3"><span className={`rounded px-2 py-1 ${product.type === "PREORDER" ? "bg-violet-50 text-violet-700" : "bg-blue-50 text-blue-600"}`}>{product.type}</span><ProductAvailabilityEditor productId={product.id} name={product.name} type={product.type} stock={product.stock} /></td><td className="p-3"><div className="flex items-center gap-2"><Link href={`/admin/products/${product.id}/edit`} aria-label={`Sửa ${product.name}`} className="rounded border border-blue-100 p-2 text-blue-600"><Pencil size={15} /></Link>{product.status !== "ARCHIVED" && <ArchiveProductButton productId={product.id} />}</div></td>
    </tr>)}{!visible.length && <tr><td colSpan={9} className="p-10 text-center text-zinc-500">Không có sản phẩm phù hợp với bộ lọc.</td></tr>}</tbody></table></div>
    <nav aria-label="Phân trang sản phẩm quản trị" className="flex justify-between border-t border-zinc-200 p-4 text-xs"><span>Hiển thị {products.length ? (page - 1) * 20 + 1 : 0}–{Math.min(page * 20, products.length)} / {products.length}</span><div className="flex gap-4">{page > 1 && <Link href={link(page - 1)} className="text-blue-600">← Trang trước</Link>}<span>{page}/{pages}</span>{page < pages && <Link href={link(page + 1)} className="text-blue-600">Trang sau →</Link>}</div></nav></section>
  </main>;
}
