import type { ProductCategorySlug } from "../src/constants/product-categories";

export type CatalogProduct = {
  name: string;
  slug: string;
  description: string;
  price: number;
  stock: number;
  type: "IN_STOCK" | "PREORDER";
  categorySlug: ProductCategorySlug;
  categorySlugs: ProductCategorySlug[];
  brandSlug: string;
  imageUrl?: string;
};

type CatalogEntry = readonly [name: string, slug: string, brandSlug: string];

const actionProducts: CatalogEntry[] = [
  ["S.H.Figuarts Son Goku - A Saiyan Raised on Earth", "shfiguarts-son-goku-saiyan-raised-on-earth", "bandai-spirits"],
  ["S.H.Figuarts Vegeta - Awakening Super Saiyan Blood", "shfiguarts-vegeta-awakening-super-saiyan-blood", "bandai-spirits"],
  ["S.H.Figuarts Piccolo - The Proud Namekian", "shfiguarts-piccolo-proud-namekian", "bandai-spirits"],
  ["S.H.Figuarts Son Gohan Beast", "shfiguarts-son-gohan-beast", "bandai-spirits"],
  ["S.H.Figuarts Orange Piccolo", "shfiguarts-orange-piccolo", "bandai-spirits"],
  ["S.H.Figuarts Frieza Fourth Form", "shfiguarts-frieza-fourth-form", "bandai-spirits"],
  ["S.H.Figuarts Trunks - The Boy from the Future", "shfiguarts-trunks-boy-from-the-future", "bandai-spirits"],
  ["S.H.Figuarts Monkey D. Luffy - Romance Dawn", "shfiguarts-luffy-romance-dawn", "bandai-spirits"],
  ["S.H.Figuarts Roronoa Zoro - Romance Dawn", "shfiguarts-zoro-romance-dawn", "bandai-spirits"],
  ["S.H.Figuarts Sanji - The Raid on Onigashima", "shfiguarts-sanji-raid-on-onigashima", "bandai-spirits"],
  ["S.H.Figuarts Monkey D. Luffy Gear 5", "shfiguarts-luffy-gear-5", "bandai-spirits"],
  ["S.H.Figuarts Trafalgar Law - The Raid on Onigashima", "shfiguarts-trafalgar-law-onigashima", "bandai-spirits"],
  ["S.H.Figuarts Naruto Uzumaki - The Jinchuriki Entrusted with Hope", "shfiguarts-naruto-uzumaki-jinchuriki", "bandai-spirits"],
  ["S.H.Figuarts Sasuke Uchiha - He Who Bears All Hatred", "shfiguarts-sasuke-uchiha-all-hatred", "bandai-spirits"],
  ["S.H.Figuarts Sakura Haruno - Inheritor of Tsunade's Will", "shfiguarts-sakura-haruno-tsunade-will", "bandai-spirits"],
  ["S.H.Figuarts Kakashi Hatake - The Famous Sharingan Hero", "shfiguarts-kakashi-hatake-sharingan-hero", "bandai-spirits"],
  ["S.H.Figuarts Itachi Uchiha NARUTOP99 Edition", "shfiguarts-itachi-uchiha-narutop99", "bandai-spirits"],
  ["S.H.Figuarts Naruto Uzumaki - Connected Thoughts", "shfiguarts-naruto-uzumaki-connected-thoughts", "bandai-spirits"],
  ["S.H.Figuarts Sasuke Uchiha - Lone Ninja", "shfiguarts-sasuke-uchiha-lone-ninja", "bandai-spirits"],
  ["S.H.Figuarts Hinata Hyuga", "shfiguarts-hinata-hyuga", "bandai-spirits"],
  ["S.H.Figuarts Shikamaru Nara", "shfiguarts-shikamaru-nara", "bandai-spirits"],
  ["S.H.Figuarts Chainsaw Man", "shfiguarts-chainsaw-man", "bandai-spirits"],
  ["S.H.Figuarts Power", "shfiguarts-power", "bandai-spirits"],
  ["S.H.Figuarts Denji", "shfiguarts-denji", "bandai-spirits"],
  ["S.H.Figuarts Loid Forger", "shfiguarts-loid-forger", "bandai-spirits"],
  ["S.H.Figuarts Anya Forger", "shfiguarts-anya-forger", "bandai-spirits"],
  ["S.H.Figuarts Yor Forger", "shfiguarts-yor-forger", "bandai-spirits"],
  ["figma Satoru Gojo", "figma-satoru-gojo", "max-factory"],
  ["figma Yuji Itadori", "figma-yuji-itadori", "max-factory"],
  ["Amazing Yamaguchi My Hero Academia Deku", "amazing-yamaguchi-deku", "kaiyodo"],
];

const scaleProducts: CatalogEntry[] = [
  ["Tino Shade 1/7", "tino-shade-1-7", "kotobukiya"],
  ["Anna Yanami 1/7", "anna-yanami-1-7", "kotobukiya"],
  ["Nina Iseri 1/7", "nina-iseri-1-7", "kotobukiya"],
  ["Tomo Ebizuka 1/7", "tomo-ebizuka-1-7", "kotobukiya"],
  ["Kana Arima 1/7", "kana-arima-1-7", "kotobukiya"],
  ["Anya Forger & Bond Forger 1/7", "anya-bond-forger-1-7", "kotobukiya"],
  ["Lucy Edgerunners 1/7", "lucy-edgerunners-1-7", "kotobukiya"],
  ["Lio Fotia 1/7", "lio-fotia-1-7", "kotobukiya"],
  ["Mamako Oosuki 1/7", "mamako-oosuki-1-7", "kotobukiya"],
  ["Red Saber 1/7", "red-saber-1-7", "kotobukiya"],
  ["Senpai 1/7", "senpai-tejina-1-7", "kotobukiya"],
  ["Ai Hinatsuru 1/7", "ai-hinatsuru-1-7", "kotobukiya"],
  ["Megumin 1/7", "megumin-1-7", "good-smile-company"],
  ["Albedo White Dress Ver. 1/7", "albedo-white-dress-1-7", "good-smile-company"],
  ["Hatsune Miku Symphony 5th Anniversary Ver. 1/1", "hatsune-miku-symphony-5th-1-1", "good-smile-company"],
  ["Ryza Reisalin 1/7", "ryza-reisalin-1-7", "good-smile-company"],
  ["Kurumi Tokisaki 1/7", "kurumi-tokisaki-1-7", "kadokawa"],
  ["Marin Kitagawa Swimsuit Ver. 1/7", "marin-kitagawa-swimsuit-1-7", "aniplex"],
  ["Zero Two For My Darling 1/7", "zero-two-for-my-darling-1-7", "good-smile-company"],
  ["Makima 1/7", "makima-1-7", "good-smile-company"],
  ["Power 1/7", "power-1-7", "good-smile-company"],
  ["Frieren 1/7", "frieren-1-7", "good-smile-company"],
  ["Fern 1/7", "fern-1-7", "good-smile-company"],
  ["Holo 1/7", "holo-1-7", "kadokawa"],
  ["Aqua Sneaker Bunko 30th Anniversary Ver. 1/7", "aqua-sneaker-bunko-30th-1-7", "kadokawa"],
  ["Emilia Crystal Dress Ver. 1/7", "emilia-crystal-dress-1-7", "kadokawa"],
  ["Rem Crystal Dress Ver. 1/7", "rem-crystal-dress-1-7", "kadokawa"],
  ["Saber Alter Dress Ver. 1/7", "saber-alter-dress-1-7", "alter"],
  ["Asuna Stacia 1/7", "asuna-stacia-1-7", "aniplex"],
  ["Ganyu Plenilune Gaze 1/7", "ganyu-plenilune-gaze-1-7", "apex"],
];

const nendoroidProducts: CatalogEntry[] = [
  ["Nendoroid Hatsune Miku", "nendoroid-hatsune-miku", "good-smile-company"],
  ["Nendoroid Frieren", "nendoroid-frieren", "good-smile-company"],
  ["Nendoroid Fern", "nendoroid-fern", "good-smile-company"],
  ["Nendoroid Himmel", "nendoroid-himmel", "good-smile-company"],
  ["Nendoroid Hitori Gotoh", "nendoroid-hitori-gotoh", "good-smile-company"],
  ["Nendoroid Nijika Ijichi", "nendoroid-nijika-ijichi", "good-smile-company"],
  ["Nendoroid Ryo Yamada", "nendoroid-ryo-yamada", "good-smile-company"],
  ["Nendoroid Ikuyo Kita", "nendoroid-ikuyo-kita", "good-smile-company"],
  ["Nendoroid Anya Forger", "nendoroid-anya-forger", "good-smile-company"],
  ["Nendoroid Loid Forger", "nendoroid-loid-forger", "good-smile-company"],
  ["Nendoroid Yor Forger", "nendoroid-yor-forger", "good-smile-company"],
  ["Nendoroid Marin Kitagawa", "nendoroid-marin-kitagawa", "good-smile-company"],
  ["Nendoroid Satoru Gojo", "nendoroid-satoru-gojo", "good-smile-company"],
  ["Nendoroid Yuji Itadori", "nendoroid-yuji-itadori", "good-smile-company"],
  ["Nendoroid Megumi Fushiguro", "nendoroid-megumi-fushiguro", "good-smile-company"],
  ["Nendoroid Nobara Kugisaki", "nendoroid-nobara-kugisaki", "good-smile-company"],
  ["Nendoroid Tanjiro Kamado", "nendoroid-tanjiro-kamado", "good-smile-company"],
  ["Nendoroid Nezuko Kamado", "nendoroid-nezuko-kamado", "good-smile-company"],
  ["Nendoroid Zenitsu Agatsuma", "nendoroid-zenitsu-agatsuma", "good-smile-company"],
  ["Nendoroid Inosuke Hashibira", "nendoroid-inosuke-hashibira", "good-smile-company"],
  ["Nendoroid Monkey D. Luffy", "nendoroid-monkey-d-luffy", "good-smile-company"],
  ["Nendoroid Roronoa Zoro", "nendoroid-roronoa-zoro", "good-smile-company"],
  ["Nendoroid Nami", "nendoroid-nami", "good-smile-company"],
  ["Nendoroid Tony Tony Chopper", "nendoroid-tony-tony-chopper", "good-smile-company"],
  ["Nendoroid Naruto Uzumaki", "nendoroid-naruto-uzumaki", "good-smile-company"],
  ["Nendoroid Sasuke Uchiha", "nendoroid-sasuke-uchiha", "good-smile-company"],
  ["Nendoroid Sakura Haruno", "nendoroid-sakura-haruno", "good-smile-company"],
  ["Nendoroid Kakashi Hatake", "nendoroid-kakashi-hatake", "good-smile-company"],
  ["Nendoroid Link Breath of the Wild Ver.", "nendoroid-link-breath-of-the-wild", "good-smile-company"],
  ["Nendoroid Zelda Breath of the Wild Ver.", "nendoroid-zelda-breath-of-the-wild", "good-smile-company"],
];

const prizeProducts: CatalogEntry[] = [
  ["Banpresto Grandista Monkey D. Luffy Gear 5", "banpresto-grandista-luffy-gear-5", "banpresto"],
  ["Banpresto Grandista Roronoa Zoro", "banpresto-grandista-roronoa-zoro", "banpresto"],
  ["Banpresto Grandista Son Goku", "banpresto-grandista-son-goku", "banpresto"],
  ["Banpresto Grandista Vegeta", "banpresto-grandista-vegeta", "banpresto"],
  ["Banpresto Vibration Stars Naruto Uzumaki", "banpresto-vibration-stars-naruto", "banpresto"],
  ["Banpresto Vibration Stars Sasuke Uchiha", "banpresto-vibration-stars-sasuke", "banpresto"],
  ["Banpresto Maximatic Gojo Satoru", "banpresto-maximatic-gojo-satoru", "banpresto"],
  ["Banpresto Q Posket Anya Forger", "banpresto-q-posket-anya-forger", "banpresto"],
  ["Banpresto Q Posket Sailor Moon", "banpresto-q-posket-sailor-moon", "banpresto"],
  ["Banpresto The Amazing Heroes Izuku Midoriya", "banpresto-amazing-heroes-izuku-midoriya", "banpresto"],
  ["Taito Coreful Hatsune Miku Uniform Ver.", "taito-coreful-hatsune-miku-uniform", "taito"],
  ["Taito Coreful Kurumi Tokisaki", "taito-coreful-kurumi-tokisaki", "taito"],
  ["Taito Coreful Mai Sakurajima", "taito-coreful-mai-sakurajima", "taito"],
  ["Taito Desktop Cute Rem", "taito-desktop-cute-rem", "taito"],
  ["Taito Desktop Cute Miku Nakano", "taito-desktop-cute-miku-nakano", "taito"],
  ["Taito AMP+ Frieren", "taito-amp-plus-frieren", "taito"],
  ["Taito AMP+ Marin Kitagawa", "taito-amp-plus-marin-kitagawa", "taito"],
  ["Taito Artist MasterPiece Hatsune Miku", "taito-artist-masterpiece-hatsune-miku", "taito"],
  ["Taito Aqua Float Girls Megumin", "taito-aqua-float-girls-megumin", "taito"],
  ["Taito Aqua Float Girls Albedo", "taito-aqua-float-girls-albedo", "taito"],
  ["SEGA Luminasta Power", "sega-luminasta-power", "sega-fave"],
  ["SEGA Luminasta Makima", "sega-luminasta-makima", "sega-fave"],
  ["SEGA Luminasta Bocchi Hitori Gotoh", "sega-luminasta-hitori-gotoh", "sega-fave"],
  ["SEGA SPM Asuka Shikinami Langley", "sega-spm-asuka-langley", "sega-fave"],
  ["SEGA SPM Rei Ayanami", "sega-spm-rei-ayanami", "sega-fave"],
  ["FuRyu BiCute Bunnies Albedo", "furyu-bicute-bunnies-albedo", "furyu"],
  ["FuRyu BiCute Bunnies Hatsune Miku", "furyu-bicute-bunnies-hatsune-miku", "furyu"],
  ["FuRyu Trio-Try-iT Yor Forger", "furyu-trio-try-it-yor-forger", "furyu"],
  ["FuRyu Trio-Try-iT Fern", "furyu-trio-try-it-fern", "furyu"],
  ["FuRyu Noodle Stopper Nezuko Kamado", "furyu-noodle-stopper-nezuko", "furyu"],
];

const resinProducts: CatalogEntry[] = [
  ["Prime 1 Studio Guts Berserker Armor 1/4", "prime1-guts-berserker-armor-1-4", "prime-1-studio"],
  ["Prime 1 Studio Griffith Falcon of Light 1/4", "prime1-griffith-falcon-of-light-1-4", "prime-1-studio"],
  ["Prime 1 Studio Eren Attack Titan 1/4", "prime1-eren-attack-titan-1-4", "prime-1-studio"],
  ["Prime 1 Studio Levi Ackerman 1/4", "prime1-levi-ackerman-1-4", "prime-1-studio"],
  ["Prime 1 Studio Alita Berserker 1/4", "prime1-alita-berserker-1-4", "prime-1-studio"],
  ["Prime 1 Studio Cloud Strife 1/4", "prime1-cloud-strife-1-4", "prime-1-studio"],
  ["Prime 1 Studio Sephiroth 1/4", "prime1-sephiroth-1-4", "prime-1-studio"],
  ["Prime 1 Studio Geralt of Rivia 1/4", "prime1-geralt-rivia-1-4", "prime-1-studio"],
  ["Prime 1 Studio Tifa Lockhart 1/4", "prime1-tifa-lockhart-1-4", "prime-1-studio"],
  ["Prime 1 Studio Vergil 1/4", "prime1-vergil-1-4", "prime-1-studio"],
  ["Prime 1 Studio Dante 1/4", "prime1-dante-1-4", "prime-1-studio"],
  ["Prime 1 Studio Jin Sakai 1/4", "prime1-jin-sakai-1-4", "prime-1-studio"],
  ["Tsume Art HQS Naruto Uzumaki", "tsume-hqs-naruto-uzumaki", "tsume-art"],
  ["Tsume Art HQS Sasuke Uchiha", "tsume-hqs-sasuke-uchiha", "tsume-art"],
  ["Tsume Art HQS Madara Uchiha", "tsume-hqs-madara-uchiha", "tsume-art"],
  ["Tsume Art Ikigai Monkey D. Luffy", "tsume-ikigai-monkey-d-luffy", "tsume-art"],
  ["Tsume Art Ikigai Roronoa Zoro", "tsume-ikigai-roronoa-zoro", "tsume-art"],
  ["Tsume Art Ikigai Tanjiro Kamado", "tsume-ikigai-tanjiro-kamado", "tsume-art"],
  ["Tsume Art Ikigai Nezuko Kamado", "tsume-ikigai-nezuko-kamado", "tsume-art"],
  ["Tsume Art HQS+ Vegeta Final Flash", "tsume-hqs-vegeta-final-flash", "tsume-art"],
  ["Infinity Studio Master Forge Geralt 1/4", "infinity-studio-geralt-1-4", "infinity-studio"],
  ["Infinity Studio Master Forge Yennefer 1/4", "infinity-studio-yennefer-1-4", "infinity-studio"],
  ["Infinity Studio League of Legends Ahri 1/4", "infinity-studio-ahri-1-4", "infinity-studio"],
  ["Infinity Studio League of Legends Jinx 1/4", "infinity-studio-jinx-1-4", "infinity-studio"],
  ["Infinity Studio Naruto Uzumaki 1/4", "infinity-studio-naruto-1-4", "infinity-studio"],
  ["Infinity Studio Sasuke Uchiha 1/4", "infinity-studio-sasuke-1-4", "infinity-studio"],
  ["Infinity Studio Dragon Ball Son Goku 1/4", "infinity-studio-son-goku-1-4", "infinity-studio"],
  ["Infinity Studio Dragon Ball Vegeta 1/4", "infinity-studio-vegeta-1-4", "infinity-studio"],
  ["Infinity Studio Evangelion Unit-01 1/4", "infinity-studio-eva-unit-01-1-4", "infinity-studio"],
  ["Infinity Studio Evangelion Asuka 1/4", "infinity-studio-asuka-1-4", "infinity-studio"],
];

const modelKitProducts: CatalogEntry[] = [
  ["Entry Grade RX-78-2 Gundam 1/144", "entry-grade-rx-78-2-gundam", "bandai-hobby"],
  ["High Grade Aerial Gundam 1/144", "hg-aerial-gundam", "bandai-hobby"],
  ["High Grade Calibarn Gundam 1/144", "hg-calibarn-gundam", "bandai-hobby"],
  ["High Grade Lfrith Gundam 1/144", "hg-lfrith-gundam", "bandai-hobby"],
  ["High Grade Rising Freedom Gundam 1/144", "hg-rising-freedom-gundam", "bandai-hobby"],
  ["High Grade Immortal Justice Gundam 1/144", "hg-immortal-justice-gundam", "bandai-hobby"],
  ["Real Grade Nu Gundam 1/144", "rg-nu-gundam", "bandai-hobby"],
  ["Real Grade Hi-Nu Gundam 1/144", "rg-hi-nu-gundam", "bandai-hobby"],
  ["Real Grade Sazabi 1/144", "rg-sazabi", "bandai-hobby"],
  ["Real Grade God Gundam 1/144", "rg-god-gundam", "bandai-hobby"],
  ["Master Grade Barbatos Gundam 1/100", "mg-barbatos-gundam", "bandai-hobby"],
  ["Master Grade Freedom Gundam 2.0 1/100", "mg-freedom-gundam-2-0", "bandai-hobby"],
  ["Master Grade Wing Gundam Zero EW Ver.Ka 1/100", "mg-wing-zero-ew-ver-ka", "bandai-hobby"],
  ["Master Grade Zeta Gundam Ver.Ka 1/100", "mg-zeta-gundam-ver-ka", "bandai-hobby"],
  ["Master Grade Eclipse Gundam 1/100", "mg-eclipse-gundam", "bandai-hobby"],
  ["Perfect Grade Unleashed RX-78-2 Gundam 1/60", "pg-unleashed-rx-78-2-gundam", "bandai-hobby"],
  ["SD Gundam EX-Standard Aerial", "sd-ex-standard-aerial", "bandai-hobby"],
  ["MGSD Freedom Gundam", "mgsd-freedom-gundam", "bandai-hobby"],
  ["MGSD Barbatos Gundam", "mgsd-barbatos-gundam", "bandai-hobby"],
  ["Figure-rise Standard Son Goku New Spec", "figure-rise-son-goku-new-spec", "bandai-hobby"],
  ["Figure-rise Standard Vegeta New Spec", "figure-rise-vegeta-new-spec", "bandai-hobby"],
  ["Figure-rise Standard Amplified Blue-Eyes White Dragon", "figure-rise-blue-eyes-white-dragon", "bandai-hobby"],
  ["Figure-rise Standard Amplified MetalGreymon", "figure-rise-metalgreymon", "bandai-hobby"],
  ["Figure-rise Standard Amplified WarGreymon", "figure-rise-wargreymon", "bandai-hobby"],
  ["Figure-rise Standard Amplified Machinedramon", "figure-rise-machinedramon", "bandai-hobby"],
  ["Figure-rise Standard Kamen Rider Kuuga", "figure-rise-kamen-rider-kuuga", "bandai-hobby"],
  ["Figure-rise Standard Kamen Rider W", "figure-rise-kamen-rider-w", "bandai-hobby"],
  ["30 Minutes Sisters SIS-G00 Rishetta", "30ms-rishetta", "bandai-hobby"],
  ["30 Minutes Sisters SIS-T00 Lirinel", "30ms-lirinel", "bandai-hobby"],
  ["30 Minutes Missions Alto White 1/144", "30mm-alto-white", "bandai-hobby"],
];

const miniBlindBoxProducts: CatalogEntry[] = [
  ["POP MART Demon Slayer Battle Series", "pop-mart-demon-slayer-battle-series", "pop-mart"],
  ["POP MART Haikyu Off-Court Vibes Series", "pop-mart-haikyu-off-court-vibes", "pop-mart"],
  ["POP MART League of Legends Clash of the Cuties", "pop-mart-lol-clash-of-the-cuties", "pop-mart"],
  ["POP MART Inuyasha Journey of Sengoku Series", "pop-mart-inuyasha-journey-sengoku", "pop-mart"],
  ["POP MART Puella Magi Madoka Magica Iconic Scenes", "pop-mart-madoka-iconic-scenes", "pop-mart"],
  ["POP MART DIMOO World x Pixar Series", "pop-mart-dimoo-world-pixar", "pop-mart"],
  ["POP MART Peach Riot Power Chords Series", "pop-mart-peach-riot-power-chords", "pop-mart"],
  ["POP MART Monster Hunter Palico Series", "pop-mart-monster-hunter-palico", "pop-mart"],
  ["POP MART Skullpanda Petals in Four Acts", "pop-mart-skullpanda-petals-four-acts", "pop-mart"],
  ["POP MART Hirono Tamed Wildgrass Series", "pop-mart-hirono-tamed-wildgrass", "pop-mart"],
  ["POP MART Kubo Love Still Series", "pop-mart-kubo-love-still", "pop-mart"],
  ["POP MART Molly Wheel of Time Anniversary Series", "pop-mart-molly-wheel-of-time", "pop-mart"],
  ["POP MART SpongeBob Krabby Patty Series", "pop-mart-spongebob-krabby-patty", "pop-mart"],
  ["POP MART Nyota We Are All Stars Series", "pop-mart-nyota-all-stars", "pop-mart"],
  ["POP MART The Monsters Hair Salon Series", "pop-mart-monsters-hair-salon", "pop-mart"],
  ["Re-Ment Pokemon Terrarium Collection", "rement-pokemon-terrarium-collection", "re-ment"],
  ["Re-Ment Pokemon Forest Collection", "rement-pokemon-forest-collection", "re-ment"],
  ["Re-Ment Pokemon Dreaming Case", "rement-pokemon-dreaming-case", "re-ment"],
  ["Re-Ment Kirby Terrarium Collection", "rement-kirby-terrarium-collection", "re-ment"],
  ["Re-Ment Kirby Dreamy Gear Collection", "rement-kirby-dreamy-gear", "re-ment"],
  ["Re-Ment Snoopy Coffee Roastery", "rement-snoopy-coffee-roastery", "re-ment"],
  ["Re-Ment Sanrio Cinnamoroll Cafe", "rement-sanrio-cinnamoroll-cafe", "re-ment"],
  ["Re-Ment Sumikko Gurashi Bakery", "rement-sumikko-gurashi-bakery", "re-ment"],
  ["Re-Ment Moomin Homestyle Dishes", "rement-moomin-homestyle-dishes", "re-ment"],
  ["Re-Ment Hatsune Miku Room", "rement-hatsune-miku-room", "re-ment"],
  ["Re-Ment My Hero Academia DesQ", "rement-my-hero-academia-desq", "re-ment"],
  ["Re-Ment Demon Slayer Hako Vision", "rement-demon-slayer-hako-vision", "re-ment"],
  ["Re-Ment Spy x Family Petit Rama", "rement-spy-family-petit-rama", "re-ment"],
  ["Re-Ment One Piece Terrarium Collection", "rement-one-piece-terrarium", "re-ment"],
  ["Re-Ment Studio Ghibli Terrarium Collection", "rement-ghibli-terrarium", "re-ment"],
];

const nendoroidDollProducts: CatalogEntry[] = [
  ["Nendoroid Doll Hatsune Miku", "nendoroid-doll-hatsune-miku", "good-smile-company"],
  ["Nendoroid Doll Snow Miku", "nendoroid-doll-snow-miku", "good-smile-company"],
  ["Nendoroid Doll Alice", "nendoroid-doll-alice", "good-smile-company"],
  ["Nendoroid Doll Mad Hatter", "nendoroid-doll-mad-hatter", "good-smile-company"],
  ["Nendoroid Doll Harry Potter", "nendoroid-doll-harry-potter", "good-smile-company"],
  ["Nendoroid Doll Ron Weasley", "nendoroid-doll-ron-weasley", "good-smile-company"],
  ["Nendoroid Doll Hermione Granger", "nendoroid-doll-hermione-granger", "good-smile-company"],
  ["Nendoroid Doll Tanjiro Kamado", "nendoroid-doll-tanjiro-kamado", "good-smile-company"],
  ["Nendoroid Doll Nezuko Kamado", "nendoroid-doll-nezuko-kamado", "good-smile-company"],
  ["Nendoroid Doll Zenitsu Agatsuma", "nendoroid-doll-zenitsu-agatsuma", "good-smile-company"],
  ["Nendoroid Doll Inosuke Hashibira", "nendoroid-doll-inosuke-hashibira", "good-smile-company"],
  ["Nendoroid Doll Link", "nendoroid-doll-link", "good-smile-company"],
  ["Nendoroid Doll Zelda", "nendoroid-doll-zelda", "good-smile-company"],
  ["Nendoroid Doll Emily", "nendoroid-doll-emily", "good-smile-company"],
  ["Nendoroid Doll Ryo", "nendoroid-doll-ryo", "good-smile-company"],
];

const collectibleDollProducts: CatalogEntry[] = [
  ["Dollfie Dream Hatsune Miku", "dollfie-dream-hatsune-miku", "volks"],
  ["Dollfie Dream Snow Miku", "dollfie-dream-snow-miku", "volks"],
  ["Dollfie Dream Sakura Miku", "dollfie-dream-sakura-miku", "volks"],
  ["Dollfie Dream Saber", "dollfie-dream-saber", "volks"],
  ["Dollfie Dream Saber Alter", "dollfie-dream-saber-alter", "volks"],
  ["Dollfie Dream Emilia", "dollfie-dream-emilia", "volks"],
  ["Dollfie Dream Rem", "dollfie-dream-rem", "volks"],
  ["Dollfie Dream Ranka Lee", "dollfie-dream-ranka-lee", "volks"],
  ["Dollfie Dream Sheryl Nome", "dollfie-dream-sheryl-nome", "volks"],
  ["Dollfie Dream 2B", "dollfie-dream-2b", "volks"],
  ["Azone PureNeemo Character Hatsune Miku", "azone-pureneemo-hatsune-miku", "azone"],
  ["Azone PureNeemo Character Rem", "azone-pureneemo-rem", "azone"],
  ["Azone PureNeemo Character Ram", "azone-pureneemo-ram", "azone"],
  ["Azone PureNeemo Character Nezuko Kamado", "azone-pureneemo-nezuko", "azone"],
  ["Azone Assault Lily Riri Hitotsuyanagi", "azone-assault-lily-riri", "azone"],
];

const imageBySlug: Record<string, string> = {
  "shfiguarts-naruto-uzumaki-connected-thoughts": "/images/products/catalog/shfiguarts-naruto-uzumaki-connected-thoughts.jpg",
  "shfiguarts-sasuke-uchiha-lone-ninja": "/images/products/catalog/shfiguarts-sasuke-uchiha-lone-ninja.jpg",
  "shfiguarts-hinata-hyuga": "/images/products/catalog/shfiguarts-hinata-hyuga.jpg",
  "shfiguarts-shikamaru-nara": "/images/products/catalog/shfiguarts-shikamaru-nara.jpg",
  "nendoroid-frieren": "/images/products/catalog/nendoroid-frieren.jpg",
};

function createProducts(
  entries: CatalogEntry[],
  categorySlugs: ProductCategorySlug[],
  basePrice: number,
): CatalogProduct[] {
  return entries.map(([name, slug, brandSlug], index) => {
    const preorder = index % 4 === 0;

    return {
      name,
      slug,
      brandSlug,
      categorySlug: categorySlugs[0],
      categorySlugs,
      description: `${name} là sản phẩm sưu tầm chính hãng, phù hợp để trưng bày và bổ sung vào bộ sưu tập cá nhân.`,
      price: basePrice + (index % 10) * 170_000,
      stock: preorder ? 0 : 4 + (index % 17),
      type: preorder ? "PREORDER" : "IN_STOCK",
      imageUrl: imageBySlug[slug],
    };
  });
}

export const catalogProducts: CatalogProduct[] = [
  ...createProducts(actionProducts, ["action-figure"], 890_000),
  ...createProducts(scaleProducts, ["scale-figure"], 1_790_000),
  ...createProducts(
    nendoroidProducts,
    ["nendoroid", "action-figure"],
    990_000,
  ),
  ...createProducts(prizeProducts, ["prize-figure"], 490_000),
  ...createProducts(
    resinProducts,
    ["resin-statue", "scale-figure"],
    8_900_000,
  ),
  ...createProducts(modelKitProducts, ["model-kit"], 390_000),
  ...createProducts(miniBlindBoxProducts, ["mini-blind-box"], 290_000),
  ...createProducts(
    nendoroidDollProducts,
    ["collectible-doll", "nendoroid", "action-figure"],
    1_290_000,
  ),
  ...createProducts(
    collectibleDollProducts,
    ["collectible-doll", "action-figure"],
    3_900_000,
  ),
];
